#!/bin/sh

while True
do
    curl --silent --output /dev/nul "http://localhost:3000/post/1"
    curl --silent --output /dev/nul "http://localhost:3000/post/2"
    curl --silent --output /dev/nul "http://localhost:3000/post/1"
    curl --silent --output /dev/nul "http://localhost:3000/post/3"
    curl --silent --output /dev/nul "http://localhost:3000/"
    curl --silent --output /dev/nul "http://localhost:3000/"
    curl --silent --output /dev/nul "http://localhost:3000/post/1232"
    curl --silent --output /dev/nul "http://localhost:3000/post/4451"
    curl --silent --output /dev/nul "http://localhost:3000/post/23111"
    curl --silent --output /dev/nul "http://localhost:3000/post/1"
    curl --silent --output /dev/nul "http://localhost:3000/post/231531"
    curl --silent --output /dev/nul "http://localhost:3000/"
    curl --silent --output /dev/nul "http://localhost:3000/post/5661"
    curl --silent --output /dev/nul "http://localhost:3000/post/33431"
    curl --silent --output /dev/nul "http://localhost:3000/post/3411"
    curl --silent --output /dev/nul "http://localhost:3000/post/31"
    curl --silent --output /dev/nul "http://localhost:3000/post/113"
    curl --silent --output /dev/nul "http://localhost:3000/post/331"
    curl --silent --output /dev/nul "http://localhost:3000/post/661"
    curl --silent --output /dev/nul "http://localhost:3000/post/134"
    curl --silent --output /dev/nul "http://localhost:3000/"
    curl --silent --output /dev/nul "http://localhost:3000/post/6661"
    curl --silent --output /dev/nul "http://localhost:3000/post/1123"
    curl --silent --output /dev/nul "http://localhost:3000/post/21"
    curl --silent --output /dev/nul "http://localhost:3000/post/1"
    curl --silent --output /dev/nul "http://localhost:3000/post/131111"
    curl --silent --output /dev/nul "http://localhost:3000/post/15666"
    curl --silent --output /dev/nul "http://localhost:3000/post/5"
    curl --silent --output /dev/nul "http://localhost:3000/post/21341"
    curl --silent --output /dev/nul "http://localhost:3000/post/23224"
    curl --silent --output /dev/nul "http://localhost:3000/post/8"
    curl --silent --output /dev/nul "http://localhost:3000/"
    sleep 1
done